    - name: inicia banco
      run: docker compose up -d postgres
      
    - name: Wait for PostgreSQL
      run: |
        until docker compose exec -T postgres pg_isready -U postgres; do
          echo 'Waiting for PostgreSQL...'
          sleep 1
        done

    - name: lint
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app golangci/golangci-lint golangci-lint run controllers/ database/ models/ routes/

    - name: Test
      run: go test -v -race -cover ./...
